######################## default configuration ####################
publishDir = "docs"
canonifyurls = true
baseURL = "https://junmakes.github.io/imayomo-web"
title = "imayomo"
theme = "bigspring"
defaultContentLanguage = "ja"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "ブログ"
url = "blog"
weight = 1

[[menu.main]]
name = "問い合わせ"
url = "contact"
weight = 2

[[menu.main]]
name = "他のアプリ"
url = "faq"
weight = 3

# footer menu left
[[menu.footer_left]]
name = "About Us"
url = "#"

[[menu.footer_left]]
name = "Quick Start"
url = "#"

[[menu.footer_left]]
name = "Pricing"
url = "pricing"


# footer menu middle
[[menu.footer_middle]]
name = "Pricing"
url = "pricing"

[[menu.footer_middle]]
name = "Platform"
url = "#"

[[menu.footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[menu.footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[menu.footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[menu.footer_right]]
name = "FAQ"
url = "faq"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Download"
link = "contact"

  
############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/junmakes"

[[params.social]]
title = "GitHub"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/junmakes"


############################# 日本語 ############################
[languages.ja]
languageName = "Ja"
title = "imayomo"
contentDir = "content/japanese" # content/japanese
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "©️junmakes"
